import Link from 'next/link';
import { ArrowRight, BarChart3, BriefcaseBusiness, CalendarDays, Check, FileText, Gift, Heart, Lightbulb, MessageCircle, Sparkles, Star, UserRound, Users } from 'lucide-react';
import { SiteFooter, SiteHeader } from '../site-shell';

const plans = [
  {n:'01',icon:MessageCircle,title:'Essential Consultation',price:'₹2,100',time:'30-40 Minutes',copy:'A focused session to explore your key questions and gain personalised numerical insights.',items:['Core numerical analysis','Key strengths & challenges','Discussion around your primary concern','Practical insights and guidance'],best:'First-time consultations and focused questions.',action:'Book Essential Session'},
  {n:'02',icon:CalendarDays,title:'In-Depth Consultation',price:'₹4,999',time:'45 Minutes + Written Report + 1 Follow-Up',copy:'A more comprehensive consultation combining detailed analysis with a documented summary of key insights.',items:['Detailed numerical analysis','Exploration of key life areas','Personal strengths & challenges','Written consultation report','One complimentary follow-up'],best:'Those seeking deeper insight and documented guidance.',action:'Book In-Depth Session',popular:true},
  {n:'03',icon:Star,title:'Premium Consultation',price:'₹6,999',time:'Up to 60 Minutes + Detailed Report + 2 Follow-Ups',copy:'A comprehensive and personalised consultation designed for deeper exploration and continued support.',items:['Comprehensive numerical analysis','Detailed discussion across relevant life areas','Personalised written report','Two complimentary follow-ups','Video consultation or in-person meeting'],best:'Those looking for a more detailed and personalised experience.',action:'Book Premium Session'},
];
const addOns=[[FileText,'Detailed Written Report','₹1,999','Receive a structured written summary of your numerical analysis, key observations and personalised recommendations.','Add Report'],[CalendarDays,'Additional Follow-Up','₹1,499','A focused follow-up session to discuss progress, questions or new developments after your consultation.','Book Follow-Up'],[MessageCircle,'Additional Question Support','₹999','Additional support for questions arising after your consultation.','Learn More']];
const why=[[Heart,'Clarity','See your questions from a clearer perspective.'],[Users,'Understanding','Recognise patterns influencing your experiences.'],[BarChart3,'Direction','Move forward with greater awareness.'],[UserRound,'Better Decisions','Use insight to approach important choices thoughtfully.']];

export default function Services(){return <main><SiteHeader/>
  <section className="services-reference-hero"><div className="services-reference-copy"><p className="eyebrow"><Sparkles size={14}/> Services &amp; consultations</p><h1>Choose the Consultation<br/>That Fits <em>Your Needs</em></h1><p>Every consultation is designed around the level of insight, analysis and support you are looking for. Choose the format that best suits your current needs.</p><div className="services-promises"><article><UserRound/><strong>Personalized Approach</strong><span>Guidance shaped around your individual circumstances.</span></article><article><CalendarDays/><strong>Flexible Consultation</strong><span>Choose the level of time and depth that suits you.</span></article><article><Star/><strong>Thoughtful Guidance</strong><span>Research-led insight focused on clarity and understanding.</span></article></div></div><div className="services-reference-photo"><img src="/assets/contact-hero-harpreet.png" alt="Harpreet Kaur"/></div><div className="services-wave"/></section>
  <div className="consultation-tabs"><span>Individual Consultations</span><span>Business Consulting <ArrowRight size={15}/></span></div>
  <section className="services-packages"><p className="eyebrow centered">Personal consultations &amp; packages</p><h2>Choose Your Level of Insight</h2><p className="services-lead">A thoughtful consultation can help you explore your questions, understand recurring patterns and gain a clearer perspective on the areas that matter most to you.</p><div className="pricing-grid">{plans.map(({n,icon:Icon,title,price,time,copy,items,best,action,popular})=><article className={popular?'popular':''} key={n}>{popular&&<span className="popular-badge">Most Popular</span>}<span className="plan-number">{n}</span><span className="plan-icon"><Icon/></span><h3>{title}</h3><strong className="plan-price">{price}</strong><b>{time}</b><p>{copy}</p><h4>Includes:</h4><ul>{items.map(item=><li key={item}><Check size={14}/>{item}</li>)}</ul><div className="best-for"><strong>Best for:</strong>{best}</div><Link href="/contact">{action}<ArrowRight size={16}/></Link></article>)}</div>
  <div className="personal-plan"><span><Gift/></span><div><h3>Looking for a Personalised Plan?</h3><p>We also offer customised packages for specific needs.<br/>Let&apos;s create a plan that is right for you.</p></div><Link className="outline-button" href="/contact">Talk to Us <ArrowRight size={15}/></Link></div></section>
  <section className="strategic-report"><div className="report-book"><span>NUMERIXX</span><strong>STRATEGIC<br/>LIFE REPORT</strong><small>✦</small></div><div><p className="eyebrow"><Sparkles size={14}/> Numerixx Strategic Life Report™</p><h2>A Deeper Look at Your Personal Patterns</h2><p>For those who prefer a comprehensive written analysis or want a permanent reference they can revisit whenever needed.</p><strong>Every report is personally researched, analysed and written by Harpreet Kaur after a detailed study of your numerical profile.</strong><div className="report-topics">{['Behavioural Patterns','Career & Business','Opportunities & Challenges','Core Strengths & Growth Areas','Relationships & Communication','Strategic Recommendations','Decision-Making Style','Current Life Phase','Action-Oriented Guidance'].map(x=><span key={x}>✦ {x}</span>)}</div></div></section>
  <section className="report-combo"><span><Lightbulb/></span><div><h3>Consultation + Strategic Report</h3><p>For clients seeking the most comprehensive experience, combining personalised one-to-one guidance with a detailed written roadmap.</p></div><Link className="outline-button" href="/contact">Enquire About This Option <ArrowRight size={15}/></Link></section>
  <section className="additional-support"><p className="eyebrow centered">Additional support</p><h2>Continue Your Journey</h2><div className="addon-grid">{addOns.map(([Icon,title,price,copy,action])=>{const I=Icon as typeof FileText;return <article key={String(title)}><span><I/></span><h3>{String(title)}</h3><strong>{String(price)}</strong><p>{String(copy)}</p><Link className="outline-button" href="/contact">{String(action)} <ArrowRight size={14}/></Link></article>})}</div></section>
  <section className="business-banner"><div><p className="eyebrow"><Sparkles size={14}/> For businesses &amp; professionals</p><h2>Looking for Strategic Business Insights?</h2><p>Explore specialised consultations designed to examine business direction, brand alignment, decision-making and behavioural dynamics through the Numerixx framework.</p><Link className="button" href="/contact">Explore Business Consulting <ArrowRight size={15}/></Link></div><img src="/assets/event-workshop-strip.png" alt="Professional business consultation"/></section>
  <section className="why-services"><div><p className="eyebrow">Why Numerixx</p><h2>People Don&apos;t Need More Predictions.<br/>They Need More Clarity.</h2></div>{why.map(([Icon,title,copy])=>{const I=Icon as typeof Heart;return <article key={String(title)}><I/><div><strong>{String(title)}</strong><p>{String(copy)}</p></div></article>})}</section>
  <section className="services-final"><div><h2>Find the Right Consultation for You</h2><p>Choose a consultation that fits your needs and begin with a deeper perspective on your questions and current circumstances.</p></div><div><Link className="gold-button" href="/contact">Book Your Consultation <ArrowRight size={15}/></Link><Link className="dark-outline" href="/contact">Let&apos;s Connect <ArrowRight size={15}/></Link></div></section>
  <SiteFooter/></main>}
