import Link from 'next/link';
import { ArrowRight, BookOpen, BriefcaseBusiness, CalendarDays, Heart, Lightbulb, Sparkles, UserRound } from 'lucide-react';
import { SiteFooter, SiteHeader } from '../site-shell';

const topics=[[UserRound,'Know Yourself','Understand your core numbers, strengths and recurring behavioural patterns.'],[Heart,'Relationships','Explore communication, compatibility and emotional responses with greater awareness.'],[BriefcaseBusiness,'Career & Business','Use numerical insight to reflect on professional choices, timing and direction.'],[CalendarDays,'Personal Cycles','Learn how personal years and recurring cycles can shape priorities and decisions.']];
const articles=[
  ['/assets/numerology-journal.jpg','Numerology Basics','What Your Life Path Number Can Reveal','A clear introduction to the patterns, strengths and lessons connected with your Life Path Number.','6 min read'],
  ['/assets/numerixx-stilllife.jpg','Self Awareness','Why the Same Patterns Keep Appearing in Your Life','Learn to recognise repeated responses and use awareness to make more thoughtful choices.','8 min read'],
  ['/assets/event-workshop-strip.png','Relationships','Understanding Communication Through Numbers','Explore how different behavioural styles communicate, connect and respond under pressure.','7 min read'],
];

export default function KnowledgeCenter(){return <main><SiteHeader/>
  <section className="knowledge-hero"><div><p className="eyebrow"><Sparkles size={14}/> Numerixx Knowledge Center</p><h1>Understand the Patterns.<br/><em>Make Clearer Choices.</em></h1><p>Research-led articles and practical insights to help you understand yourself, your relationships and the decisions shaping your life.</p><Link className="button" href="#latest-insights">Explore Insights <ArrowRight size={16}/></Link></div><div className="knowledge-hero-art"><img src="/assets/numerology-journal.jpg" alt="Numerology research journal"/><span className="floating-note"><BookOpen/><b>Research-led learning</b><small>Clear, practical and thoughtful</small></span></div></section>
  <section className="knowledge-topics"><div className="knowledge-heading"><p className="eyebrow">Explore by topic</p><h2>Start With What Matters to You</h2><p>Choose an area and discover practical ideas you can use in everyday life.</p></div><div className="knowledge-topic-grid">{topics.map(([Icon,title,copy])=>{const I=Icon as typeof Heart;return <article key={String(title)}><span><I/></span><h3>{String(title)}</h3><p>{String(copy)}</p><a href="#latest-insights">Explore topic <ArrowRight size={14}/></a></article>})}</div></section>
  <section className="featured-insight"><img src="/assets/harpreet-portrait-provided.png" alt="Harpreet Kaur"/><div><p className="eyebrow"><Sparkles size={14}/> Featured insight</p><h2>Numbers Don&apos;t Control Your Life. They Help You Notice It.</h2><p>Numerology becomes useful when it helps you recognise consistent tendencies—how you make decisions, communicate, respond to change and navigate important phases of life.</p><p>The goal is not prediction. It is clearer self-understanding and more conscious action.</p><Link className="text-link" href="/contact">Discuss your patterns <ArrowRight size={15}/></Link></div></section>
  <section className="latest-insights" id="latest-insights"><p className="eyebrow centered">Latest insights</p><h2>Learn, Reflect and Grow</h2><div className="insight-grid">{articles.map(([image,category,title,copy,time])=><article key={String(title)}><img src={String(image)} alt=""/><div><span>{String(category)} · {String(time)}</span><h3>{String(title)}</h3><p>{String(copy)}</p><a href="/contact">Read insight <ArrowRight size={14}/></a></div></article>)}</div></section>
  <section className="knowledge-note"><Lightbulb/><div><p className="eyebrow">A thoughtful reminder</p><h2>Awareness is where meaningful change begins.</h2><p>Use these resources as a starting point for reflection. Personalised consultation can help you explore the patterns most relevant to your circumstances.</p></div><Link className="gold-button" href="/contact">Book a Consultation <ArrowRight size={15}/></Link></section>
  <SiteFooter/></main>}
