'use client';
import { AtSign, CalendarDays, ChevronRight, Clock3, ExternalLink, Mail, MapPin, MessageCircle, Phone, Send, ShieldCheck, Sparkles, UserRound } from 'lucide-react';
import { SiteFooter, SiteHeader } from '../site-shell';

const connect = [[CalendarDays,'Book an Appointment','Schedule your session at a time that works best for you.'],[MessageCircle,'Chat on WhatsApp','Quick questions? Message us directly on WhatsApp.'],[Mail,'Email Us','Drop us an email anytime. We typically respond within 24 hours.'],[AtSign,'Follow Us','Stay inspired and updated. Follow us on Instagram.']];
const faqs = [['How do I book a consultation?','Choose a date and time below, then confirm your booking. We will contact you with the next steps.'],['Are sessions available online?','Yes. Sessions are available worldwide through Google Meet.'],['What is your cancellation policy?','Please let us know at least 24 hours before your appointment if you need to reschedule.'],['Do you offer customized reports?','Yes. Customised reports can be discussed during your initial consultation.']];
const dates = Array.from({length:31},(_,i)=>i+1);

export default function Contact(){return <main><SiteHeader/>
  <section className="contact-reference-hero"><div className="contact-reference-copy"><span className="breadcrumb">Home　›　Contact Us</span><p className="eyebrow"><Sparkles size={14}/> We&apos;re here for you</p><h1>Let&apos;s Connect &amp;<br/>Create Clarity Together</h1><div className="gold-rule"/><p>Have a question, need guidance, or ready to start your journey? We&apos;d love to hear from you.</p><div className="contact-highlights"><div><Phone/><strong>Phone</strong><span>+91 98765 43210</span></div><div><Mail/><strong>Email</strong><span>hello@numerixx.com</span></div><div><Clock3/><strong>Hours</strong><span>Mon - Sat: 10AM - 7PM (IST)</span></div></div></div><div className="contact-reference-photo"><img src="/assets/harpreet-hero.jpg" alt="Harpreet Kaur"/></div></section>
  <section className="contact-reference-body"><div className="contact-panels"><form className="message-panel" onSubmit={e=>e.preventDefault()}><h2>Send Us a Message</h2><p>Fill out the form below and we&apos;ll get back to you as soon as possible.</p><div className="form-two"><label><UserRound/><input aria-label="Your name" placeholder="Your Name"/></label><label><Mail/><input aria-label="Email address" type="email" placeholder="Email Address"/></label></div><label><Phone/><input aria-label="Phone number" type="tel" placeholder="Phone Number"/></label><select aria-label="Service of interest" defaultValue=""><option value="" disabled>I&apos;m interested in</option><option>Personal Numerology Consultation</option><option>Relationship Guidance</option><option>Business Numerology</option><option>Career Guidance</option></select><textarea aria-label="Your message" placeholder="Your Message"/><button type="submit">Send Message <Send size={16}/></button><small><ShieldCheck size={14}/> Your information is 100% confidential and secure.</small></form>
    <section className="connect-panel"><h2>Other Ways to Connect</h2>{connect.map(([Icon,title,copy])=>{const I=Icon as typeof Mail; return <a href={String(title).includes('WhatsApp')?'https://wa.me/919876543210':String(title).includes('Email')?'mailto:hello@numerixx.com':'#booking'} key={String(title)}><span className="connect-icon"><I/></span><span><strong>{String(title)}</strong><small>{String(copy)}</small></span><ChevronRight/></a>})}<blockquote>“ Every meaningful conversation<br/>begins with connection. ”</blockquote></section></div>
    <section className="booking-reference" id="booking"><div className="booking-intro"><p className="eyebrow"><CalendarDays size={14}/> Book a consultation</p><h2>Schedule Your Session</h2><p>Choose a date and time that works for you. We look forward to connecting!</p><ul><li><UserRound/>Personalized 1:1 Consultation</li><li><ShieldCheck/>Secure &amp; Confidential Sessions</li><li><MessageCircle/>Virtual Meeting (Google Meet)</li></ul></div><div className="calendar-card"><header><button aria-label="Previous month">‹</button><strong>September 2026</strong><button aria-label="Next month">›</button></header><div className="calendar-days"><b>MON</b><b>TUE</b><b>WED</b><b>THU</b><b>FRI</b><b>SAT</b><b>SUN</b>{dates.map(d=><span className={d===23?'selected':''} key={d}>{d}</span>)}</div></div><div className="time-card"><strong>Wednesday, 23 September</strong>{['10:00 AM','11:30 AM','02:00 PM','04:30 PM','06:00 PM'].map(t=><button className={t==='02:00 PM'?'selected':''} key={t}>{t}</button>)}</div><div className="session-card"><strong>Your Session</strong><dl><dt>Date</dt><dd>Wed, 23 Sep 2026</dd><dt>Time</dt><dd>02:00 PM - 02:45 PM</dd><dt>Duration</dt><dd>45 Minutes</dd><dt>Platform</dt><dd>Google Meet</dd></dl><button>Confirm Booking <CalendarDays size={15}/></button><small>You can reschedule or cancel anytime.</small></div></section>
    <section className="location-reference"><div><h2>Our Location</h2><p><MapPin/> <strong>Numerixx Consulting</strong><br/>Mohali, Punjab, India</p><small>Serving clients across India and worldwide through online sessions.</small><a href="https://maps.google.com" target="_blank">Get Directions <ExternalLink size={13}/></a></div><div className="map-art"><span><MapPin/></span></div><div><h2>Office Details</h2><p><Phone/> +91 98765 43210</p><p><Mail/> hello@numerixx.com</p><p><Clock3/> Mon - Sat: 10AM - 7PM (IST)</p></div></section>
    <section className="faq-reference"><p className="eyebrow"><Sparkles size={14}/> Quick answers</p><h2>Frequently Asked Questions</h2>{faqs.map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</section>
  </section><SiteFooter/></main>}
