import { ArrowRight, BarChart3, CalendarDays, Clock3, Flower2, Heart, Lightbulb, MapPin, Sparkles, Star, UserRound, Users } from 'lucide-react';
import { SiteFooter, SiteHeader } from '../site-shell';

const benefits = [[UserRound,'Practical Insights','Real-world Numerology knowledge you can apply immediately.'],[Flower2,'Personal Growth','Understand your numbers and unlock your true potential.'],[Users,'Expert Guidance','Learn from Dr. Harpreet Kaur, an experienced Numerologist and Coach.'],[Star,'Life Transformation','Make informed decisions and create a more balanced, successful life.']];
const agenda = [[BarChart3,'Introduction to Numerology','10:00 AM - 11:00 AM'],[Lightbulb,'Your Life Path Number','11:15 AM - 12:30 PM'],[Heart,'Personal Year & Compatibility','1:30 PM - 2:30 PM'],[Sparkles,'Q&A & Practical Applications','2:45 PM - 4:00 PM']];
const past = [
  ['0%','12 April 2025','Unlocking Life Purpose Through Numbers','An inspiring session on discovering life purpose and direction.'],
  ['33.333%','22 March 2025','Numerology & Relationships Workshop','Exploring compatibility, relationships and the power of understanding.'],
  ['66.667%','15 February 2025','Personal Year Predictions Masterclass','Deep dive into personal year cycles and future opportunities.'],
  ['100%','18 January 2025','Numerology for Career & Success','Align your numbers with your career path and professional growth.'],
];

export default function Event(){return <main><SiteHeader/>
  <section className="event-hero"><div className="event-hero-copy"><p className="eyebrow"><Sparkles size={14}/> Live event</p><h1>Numerology Workshop<br/>for a Meaningful Life</h1><div className="gold-rule"/><h2>Discover the Power of Numbers</h2><p>Learn how Numerology can help you understand your purpose, overcome challenges, and create a life aligned with your true potential.</p><div className="event-meta"><article><CalendarDays/><div><strong>Date</strong><span>25 May 2025</span></div></article><article><Clock3/><div><strong>Time</strong><span>10:00 AM - 4:00 PM</span></div></article><article><MapPin/><div><strong>Location</strong><span>Numerixx Consulting<br/>Mohali, Punjab, India</span></div></article></div><div className="event-actions"><a className="button" href="#event-booking">Book Your Seat <ArrowRight size={16}/></a><a className="outline-button" href="#event-agenda">Learn More</a></div></div><div className="event-hero-photo"><img src="/assets/harpreet-hero.jpg" alt="Dr. Harpreet Kaur, Numerixx workshop host"/></div><div className="event-wave"/></section>
  <section className="event-benefits">{benefits.map(([Icon,title,copy])=>{const I=Icon as typeof Star;return <article key={String(title)}><span><I/></span><h3>{String(title)}</h3><p>{String(copy)}</p></article>})}</section>
  <section className="event-agenda" id="event-agenda"><p className="eyebrow centered">Event agenda</p><h2>What You&apos;ll Learn</h2><div className="agenda-grid">{agenda.map(([Icon,title,time],i)=>{const I=Icon as typeof Heart;return <article key={String(title)}><span className="agenda-icon"><I/></span><div><small>0{i+1}</small><h3>{String(title)}</h3><p>{String(time)}</p></div></article>})}</div></section>
  <section className="past-events"><p className="eyebrow centered">Past events</p><h2>Moments of Learning &amp; Transformation</h2><div className="past-grid">{past.map(([position,date,title,copy])=><article key={String(title)}><div className="past-event-photo" role="img" aria-label={String(title)} style={{backgroundPosition:`${position} center`}}/><div><span><CalendarDays size={13}/> {String(date)}</span><h3>{String(title)}</h3><p>{String(copy)}</p><a href="#event-booking">View Highlights <ArrowRight size={14}/></a></div></article>)}</div><a className="outline-button all-events" href="#event-booking">View All Past Events</a></section>
  <section className="event-speaker"><img src="/assets/harpreet-hero.jpg" alt="Dr. Harpreet Kaur"/><div><p className="eyebrow">Featured speaker</p><h2>Dr. Harpreet Kaur</h2><h3>Founder &amp; Lead Numerologist</h3><div className="gold-rule"/><p>A renowned Numerologist and Life Coach with years of experience helping individuals and businesses align with their true purpose through the power of numbers.</p></div></section>
  <section className="event-booking" id="event-booking"><div><CalendarDays/><span><strong>Limited Seats<br/>Available!</strong><small>Don&apos;t miss this opportunity<br/>to transform your life.</small></span></div><div className="event-price"><strong>₹2,499</strong><span>Per Person</span><small>Early Bird Offer Available</small></div><div><a className="gold-button" href="mailto:hello@numerixx.com?subject=Numerology Workshop Booking">Book Your Seat Now <ArrowRight size={16}/></a><small>Secure Payment | 100% Safe</small></div></section>
  <SiteFooter/>
  </main>}
