import Link from 'next/link';
import { ArrowUpRight, BriefcaseBusiness, Compass, Flower2, Heart, Rocket, Sparkles, Target, UsersRound, UserRound } from 'lucide-react';
import { SiteFooter, SiteHeader } from './site-shell';
const coreServices=[[UserRound,'Personal Numerology Reading','Understand your core numbers and life purpose with clarity.'],[BriefcaseBusiness,'Career & Business Guidance','Make confident career moves and smart business decisions.'],[Heart,'Relationship Compatibility','Improve understanding and build stronger, healthier relationships.'],[Flower2,'Life Path & Personal Growth','Navigate challenges and embrace growth with purpose.']];
const patterns=[[UserRound,'Personal Clarity'],[Compass,'Life Direction & Decision'],[BriefcaseBusiness,'Career & Professional Growth'],[Heart,'Relationship & Marriage'],[UsersRound,'Family & Parenting'],[Rocket,'Business & Entrepreneurship'],[Flower2,'Health & Lifestyle Behaviour'],[Target,'Name Analysis & Correction']];
const journeys=[['01','Business Strategy','Understand behavioural and numerical patterns that may influence leadership and business direction.'],['02','Professional Growth','Identify strengths and opportunities for greater clarity in your career.'],['03','Business Relationships','Explore communication styles and partnership dynamics.'],['04','Personal Direction','Gain perspective on the system influencing your current life phase.'],['05','Relationships','Understand compatibility and recurring dynamics in important relationships.'],['06','Life Transitions','Navigate periods of change with a more structured approach.']];
export default function Home(){return <main><SiteHeader/>
  <section className="pdf-hero"><div className="pdf-hero-copy"><p className="eyebrow"><Sparkles size={15}/> Welcome,</p><h1>I’m<br/><em>Harpreet Kaur</em></h1><p className="hero-role">Researcher · Strategic Consultant · Human Behaviour Practitioner</p><div className="ornament"><span/>✦<span/></div><h2>Personalised guidance for every stage of life</h2><p>Whether you’re facing uncertainty, making an important decision, or seeking deeper self-understanding, my consultations help you recognise recurring patterns and move forward with clarity.</p><Link className="button" href="/services">Explore Numerixx <ArrowUpRight size={16}/></Link><img className="pdf-stilllife" src="/assets/numerixx-stilllife.jpg" alt="Numerology books, candle and crystal"/></div><div className="pdf-portrait"><img src="/assets/harpreet-hero.jpg" alt="Harpreet Kaur"/></div><div className="curve-divider"/></section>
  <section className="section pdf-services"><div className="section-heading"><p className="eyebrow centered"><Sparkles size={14}/> How I can help</p><h2>Services</h2><p>Insightful guidance tailored to your unique journey.</p></div><div className="service-grid">{coreServices.map(([Icon,title,copy],i)=><article className="service-card" key={String(title)}><span className="number">0{i+1}</span><span className="icon"><Icon/></span><h3>{String(title)}</h3><p>{String(copy)}</p><Link href="/services">Learn more <ArrowUpRight size={14}/></Link></article>)}</div></section>
  <section className="pdf-approach"><img src="/assets/numerology-journal.jpg" alt="Numerology journal and crystals"/><div><p className="eyebrow"><Sparkles size={14}/> My approach</p><h2>Clarity. Insight. Transformation.</h2><p>I combine ancient wisdom, numerical pattern analysis and a modern understanding of human behaviour to help you decode recurring patterns and make more informed decisions.</p><ul><li><strong>In-depth Analysis</strong><span>A deeper look at your numerical and behavioural patterns.</span></li><li><strong>Personal & Empathetic Guidance</strong><span>Thoughtful guidance that considers your unique circumstances.</span></li><li><strong>Actionable Insights</strong><span>Practical direction you can confidently apply in real life.</span></li></ul></div></section>
  <section className="section explore-patterns"><div className="pattern-heading"><div><p className="eyebrow"><Sparkles size={14}/> Personal guidance</p><h2>Explore Your<br/><em>Patterns</em></h2><p>Understand yourself, navigate challenges and make decisions aligned with your values.</p></div><img src="/assets/numerixx-stilllife.jpg" alt="Books, candle, flowers and crystal"/></div><div className="pattern-grid">{patterns.map(([Icon,title])=><article key={String(title)}><span className="icon"><Icon/></span><h3>{String(title)}</h3><span className="tiny-ornament">— ✦ —</span><p>Discover clearer perspective, meaningful insight and practical next steps.</p></article>)}</div><div className="quote-strip">“ Every number tells a story. Together, they reveal patterns worth understanding. ”<small>Let’s decode yours.</small></div></section>
  <section className="section guidance"><div className="guidance-head"><div><p className="eyebrow">Business & life intelligence</p><h2>Insight and Guidance for Navigating the <em>Professional and Personal Areas of Life</em> that Matter Most.</h2></div><img src="/assets/reference-home.png" alt="A path toward the horizon with a compass"/></div><div className="guidance-grid">{journeys.map(([n,title,copy])=><article key={n}><span>{n}</span><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div><p className="guidance-line">Focused insight. Clearer decisions. Meaningful direction.</p></section>
  <section className="chapter"><div><p className="eyebrow centered"><Sparkles size={14}/> What I offer</p><h2>Services for Every<br/><em>Chapter of Life</em></h2><p>Guidance and insight for the challenges, decisions and transitions that shape different chapters of your life.</p><Link className="button gold" href="/services">Explore all services <ArrowUpRight size={16}/></Link></div><img src="/assets/numerixx-stilllife.jpg" alt="A calm still life with candle and crystal"/></section>
  <section className="home-contact"><div><p className="eyebrow"><Sparkles size={14}/> How we connect</p><h2>A Simple Way to Connect,<br/>Explore Your Needs and<br/>Take the <em>Next Step</em></h2><p>Connecting with Numerixx starts with a simple conversation.</p><Link className="button" href="/contact">See how we connect <ArrowUpRight size={16}/></Link></div><img src="/assets/reference-home.png" alt="A path symbolising the next step"/></section>
  <SiteFooter/></main>}
