import Link from 'next/link';
import { ArrowRight, BarChart3, Check, FileText, Handshake, Headphones, Lightbulb, MessageCircle, Sparkles, Tag, Target, Users, UserRound } from 'lucide-react';
import { SiteFooter, SiteHeader } from '../site-shell';

const areas=[[UserRound,'Founder & Leadership Analysis','Understand leadership strengths, decision-making style and personal impact.'],[BarChart3,'Business Behaviour Assessment','Explore the behavioural patterns influencing your business decisions and operations.'],[Tag,'Brand & Name Analysis','Analyse your brand or business name for alignment, resonance and long-term potential.'],[Handshake,'Partnership Compatibility','Evaluate compatibility in partnerships, collaborations and key business relationships.'],[Target,'Strategic Decision Support','Gain numerical perspectives to support important business and strategic decisions.'],[Users,'Team Dynamics','Understand team energy, roles, collaboration patterns and collective strengths.']];
const addOns=[[FileText,'Detailed Written Report','₹1,999'],[MessageCircle,'Additional Follow-Up','₹1,499'],[Lightbulb,'Additional Question Support','₹999']];

export default function BusinessConsulting(){return <main><SiteHeader/>
  <section className="services-reference-hero business-page-hero"><div className="services-reference-copy"><Link className="hero-back-link" href="/services">← Back to Services</Link><p className="eyebrow"><Sparkles size={14}/> Numerixx business intelligence</p><h1>Strategic Insight for<br/>Businesses, Brands &amp;<br/><em>Professionals</em></h1><p>A structured approach to exploring business behaviour, decision-making, brand alignment and growth through numerical and human behaviour analysis.</p><div className="services-promises"><article><BarChart3/><strong>Research-led Insight</strong><span>Analysis backed by structured study and experience.</span></article><article><Target/><strong>Strategic Direction</strong><span>Focused guidance for important business decisions.</span></article><article><Users/><strong>Professional Clarity</strong><span>Personalised insight for leaders, teams and brands.</span></article></div></div><div className="services-reference-photo"><img src="/assets/contact-hero-harpreet.png" alt="Harpreet Kaur providing strategic business guidance"/></div><div className="services-wave"/></section>
  <section className="business-areas">{areas.map(([Icon,title,copy])=>{const I=Icon as typeof Target;return <article key={String(title)}><span><I/></span><h3>{String(title)}</h3><i>— ✦ —</i><p>{String(copy)}</p></article>})}</section>
  <section className="business-help"><Headphones/><div><h2>Not sure which consultation is right for you?</h2><p>Our team can help you choose the most suitable option.</p></div><ul><li><Check/>What services we offer</li><li><Check/>Which package is suitable</li><li><Check/>Pricing &amp; availability</li></ul><Link className="button" href="/contact">Talk to our team <ArrowRight size={15}/></Link></section>
  <section className="business-report-grid"><article className="business-report dark"><div className="business-report-content"><p className="eyebrow"><Sparkles size={14}/> Numerixx Strategic Life Report™</p><h2>Your Personal Blueprint<br/>for Clarity &amp; Direction</h2><p>A comprehensive written analysis providing a deeper understanding of patterns, strengths, challenges and opportunities. Every report is personally researched and written.</p><div className="business-report-list">{['Behavioural Patterns','Core Strengths & Growth Areas','Decision-Making Style','Career & Business','Relationships & Communication','Current Life Phase','Opportunities & Challenges','Strategic Recommendations'].map(x=><span key={x}>✦ {x}</span>)}</div><Link className="gold-button" href="/contact">Enquire about the report <ArrowRight size={15}/></Link></div><div className="report-visual report-book-visual" role="img" aria-label="Numerixx Strategic Life Report book"><div><small>NUMERIXX</small><strong>STRATEGIC<br/>LIFE REPORT</strong><span>✦</span></div></div></article><article className="business-report light"><div className="business-report-content"><p className="eyebrow"><Sparkles size={14}/> Consultation + strategic report</p><h2>The Most Comprehensive Experience</h2><p>Combine a personalised one-to-one consultation with the Numerixx Strategic Life Report™, giving you live guidance and a detailed written roadmap.</p><ul>{['In-depth one-to-one consultation','Personalised written strategic report','Detailed life analysis & guidance','Two-way clarity: live + written','Long-term reference for decision-making'].map(x=><li key={x}><Check/>{x}</li>)}</ul><Link className="button" href="/contact">Explore this option <ArrowRight size={15}/></Link></div><div className="report-visual report-paper-visual" role="img" aria-label="Personalised strategic report document"><div><small>NUMERIXX</small><strong>STRATEGIC<br/>LIFE REPORT</strong><span>✦</span><i/><i/><i/></div></div></article></section>
  <section className="business-addons"><div><p className="eyebrow"><Sparkles size={14}/> Add-on services</p><h2>Enhance Your Consultation</h2></div><div className="business-addon-grid">{addOns.map(([Icon,title,price])=>{const I=Icon as typeof FileText;return <article key={String(title)}><I/><h3>{String(title)}</h3><strong>{String(price)}</strong><Link href="/contact">Learn more <ArrowRight size={14}/></Link></article>})}</div></section>
  <section className="services-final"><div><h2>Find the Right Consultation for You</h2><p>Choose a consultation that fits your needs and begin with a deeper perspective on your business, brand and professional direction.</p></div><div><Link className="gold-button" href="/contact">Book Your Consultation <ArrowRight size={15}/></Link><Link className="dark-outline" href="/contact">Let&apos;s Connect <ArrowRight size={15}/></Link></div></section>
  <SiteFooter/></main>}
